#  Date: 18.01.2025
# 
#  Author: Amanda Uccello
#  Class: ICS4UR-1
#  School: Port Credit Secondary School
#  Teacher: Mrs. Kim
#  Description: 
#      Docker compose file to start weaviate vector database 
#      and postgres regular database.

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"  # port for the weaviate server
      - "50051:50051" # grpc port
      - "8300:8300"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai' # use openai text2vec to vectorize
      ENABLE_MODULES: 'text2vec-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  weaviate_data:
  postgres_data: