services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
      - "8300:8300"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
      # RAFT_BOOTSTRAP_EXPECT: '1'
      # DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      # ENABLE_MODULES: text2vec-transformers
      # TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      # CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    # depends_on:
    #  - t2v-transformers

  # t2v-transformers:
  #  image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
  #  environment:
  #    ENABLE_CUDA: 0 # set to 1 to enable

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  weaviate_data:
  postgres_data: